config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  resource :cart, only: :show
  resources :products, only: [] do
    resources :line_items, only: :create
  end
  resources :line_items, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def total_price
    PricingRules.new(self).calculate_discounts
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  validates :quantity, numericality: { greater_than: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  has_one_attached :photo
  validates :product_code, :name, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_cart
  helper_method :current_cart

  private

  def current_cart
    if session[:cart_id]
      @current_cart ||= Cart.find(session[:cart_id])
    else
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
    @current_cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = current_cart
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    product = Product.find(params[:product_id])
    line_item = current_cart.line_items.find_by(product: product)

    if line_item
      line_item.quantity += line_item_params[:quantity].to_i
    else
      line_item = current_cart.line_items.build(product: product, quantity: line_item_params[:quantity].to_i, price: product.price)
    end

    respond_to do |format|
      if line_item.save
        flash[:notice] = 'Added to the basket!'
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("form_product_#{product.id}", partial: 'products/form', locals: { product: product, line_item: LineItem.new }),
            turbo_stream.update('flash', partial: 'shared/flashes')
          ]
        end
        format.html { redirect_to root_path, notice: 'Added to the basket!' }
      else
        flash[:alert] = 'Product could not be added'
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update("form_product_#{product.id}", partial: 'products/form', locals: { product: product, line_item: line_item }),
            turbo_stream.update('flash', partial: 'shared/flashes')
          ], status: :unprocessable_entity
        end
        format.html { render 'products/index', alert: "Product could not be added", status: :unprocessable_entity }
      end
    end
  end

  def destroy
    line_item = LineItem.find(params[:id])
    respond_to do |format|
      if line_item.destroy
        flash[:notice] = 'Removed product!'
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update('line_items', partial: 'carts/table', locals: { cart: current_cart }),
            turbo_stream.update('flash', partial: 'shared/flashes')
          ]
        end
        format.html { redirect_to cart_path, notice: 'Removed product!' }
      else
        flash[:alert] = 'Product could not be removed'
        format.turbo_stream do
          render turbo_stream: [
            turbo_stream.update('line_items', partial: 'carts/table', locals: { cart: current_cart }),
            turbo_stream.update('flash', partial: 'shared/flashes')
          ], status: :unprocessable_entity
        end
        format.html { render 'carts/show', alert: "Product could not be removed", status: :unprocessable_entity }
      end
    end
  end

  private

  def line_item_params
    params.require(:line_item).permit(:quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @line_item = LineItem.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_line_item.html.erb
<tr id='<%= line_item.product.id %>'>
  <td class='border-0'><%= line_item.product.name %> (<%= line_item.product.product_code %>)</td>
  <td class='border-0'><%= line_item.quantity %></td>
  <td class='border-0'>
    <div class='d-flex justify-content-between'>
      <%= line_item.price %> €
      <%= link_to line_item_path(line_item), data: { turbo_method: :delete } do %>
        <%= image_tag 'trash-icon.png', height: 20, width: 20, alt: 'remove product icon' %>
      <% end %>
    </div>
  </td>
  <td class='border-0'></td>
</tr>

app/views/carts/_table.html.erb
<table class='table mb-0'>
  <thead>
    <th scope='col'>Name</th>
    <th scope='col'>Quantity</th>
    <th scope='col'>Unit Price</th>
  </thead>
  <tbody>
  <% cart.line_items.each_with_index do |line_item, index| %>
    <%= render 'carts/line_item', line_item: line_item, index: index %>
  <% end %>
  <tr>
    <td class='border-0'></td>
    <td class='border-0 fw-bold'>Total Price:</td>
    <td class='border-0' id='total-price'><%= cart.total_price %> € (with discounts)</td>
  </tr>
  </tbody>
</table>

app/views/carts/show.html.erb
<h1>Summary</h1>
<div class='border px-4 py-2 rounded'>
  <%= turbo_frame_tag :line_items do %>
    <%= render 'table', cart: @cart %>
  <% end %>
</div>
<div class='my-5 text-end'>
  <%= link_to 'Pay', '#', class: 'btn btn-primary fw-bold py-2 px-5' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashRegister</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script async src="https://ga.jspm.io/npm:es-module-shims@1.8.2/dist/es-module-shims.js" data-turbo-track="reload"></script>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for [product, line_item], url: product_line_items_path(product), html: { class: 'd-flex flex-column flex-wrap align-content-end' }  do |f| %>
  <div data-controller='quantity'>
    <div class='input-group justify-content-center'>
      <button type='button' class='btn btn-light height-fit-content fw-bold light-border px-3 py-2' data-action='click->quantity#decrement'>-</button>
      <%= f.input :quantity, label: false, input_html: { class: 'form-control py-2 light-border-top-bottom border-left-0 border-right-0 rounded-0', value: 1, min: 1, max: 100, data: { quantity_target: 'input' } } %>
      <button type='button' class='btn btn-light height-fit-content fw-bold light-border px-3 py-2' data-action='click->quantity#increment'>+</button>
    </div>
  </div>
  <%= f.submit 'Add', class: 'btn btn-primary height-fit-content py-2 px-5 fw-bold' %>
<% end %>

app/views/products/_product.html.erb
<div class='col-12 col-md-6 col-lg-4'>
  <div class='product-card rounded'>
    <% if product.photo.attached? %>
      <%= cl_image_tag product.photo.key, class: 'img-fluid rounded', alt: product.name %>
    <% else %>
      <%= image_tag 'default-image.webp', class: 'img-fluid', alt: 'placeholder grey image' %>
    <% end %>
    <div class='product-card-bottom p-4'>
      <h3><%= product.name %></h3>
      <p class='mb-4'>Price: <%= product.price %> €</p>
      <%= turbo_frame_tag dom_id(product, :form) do %>
        <%= render 'form', product: product, line_item: line_item %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<h1>Products</h1>
<div class='row g-5 product-grid'>
  <% @products.each do |product| %>
    <%= render 'product', product: product, line_item: @line_item %>
  <% end %>
</div>
<div class='my-5 text-end'>
  <%= link_to 'Checkout', cart_path, class: 'btn btn-primary fw-bold py-2 px-5' %>
</div>

app/views/shared/_flashes.html.erb
<%= turbo_frame_tag :flash do %>
  <% if notice %>
    <div class="alert alert-info alert-dismissible fade show m-1 w-100 position-fixed w-100 top-0 start-50 translate-middle-x z-3" role="alert" data-controller="flashes">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-warning alert-dismissible fade show m-1 position-fixed w-100 top-0 start-50 translate-middle-x z-3" role="alert" data-controller="flashes">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= alert %>
    </div>
  <% end %>
  <% flash.clear %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class='d-flex justify-content-between align-items-center p-4' aria-label='Main navigation'>
  <div class='logo'>
    <%= link_to root_path do %>
      <%= image_tag 'logo.webp', alt: 'Shopping cart Logo', width: 100, height: 100 %>
    <% end %>
  </div>

  <ul class='nav-links d-flex ms-auto list-unstyled text-'>
    <li class='me-4'>
      <h5><%= link_to 'Products', root_path, class: 'd-block navbar-link', 'aria-current': (current_page?(root_path) ? 'page' : nil) %></h5>
    </li>
    <li>
      <h5><%= link_to 'Checkout', cart_path, class: 'd-block navbar-link', 'aria-current': (current_page?(cart_path) ? 'page' : nil) %></h5>
    </li>
  </ul>
</nav>